from itertools import islice

# Predefined set of 100 most asked LeetCode problems with pattern
leetcode_questions = [
    # Format: (Title, Pattern, URL)
    ("Two Sum", "Hash Map", "https://leetcode.com/problems/two-sum/"),
    ("Best Time to Buy and Sell Stock", "Greedy", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"),
    ("Contains Duplicate", "Hash Map", "https://leetcode.com/problems/contains-duplicate/"),
    ("Product of Array Except Self", "Prefix/Suffix", "https://leetcode.com/problems/product-of-array-except-self/"),
    ("Maximum Subarray", "Kadane’s Algorithm", "https://leetcode.com/problems/maximum-subarray/"),
    ("Maximum Product Subarray", "Dynamic Programming", "https://leetcode.com/problems/maximum-product-subarray/"),
    ("Find Minimum in Rotated Sorted Array", "Binary Search", "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"),
    ("Search in Rotated Sorted Array", "Binary Search", "https://leetcode.com/problems/search-in-rotated-sorted-array/"),
    ("3Sum", "Two Pointers", "https://leetcode.com/problems/3sum/"),
    ("Container With Most Water", "Two Pointers", "https://leetcode.com/problems/container-with-most-water/"),
    ("Valid Parentheses", "Stack", "https://leetcode.com/problems/valid-parentheses/"),
    ("Merge Intervals", "Sorting", "https://leetcode.com/problems/merge-intervals/"),
    ("Insert Interval", "Intervals", "https://leetcode.com/problems/insert-interval/"),
    ("Group Anagrams", "Hash Map", "https://leetcode.com/problems/group-anagrams/"),
    ("Valid Anagram", "Hash Map", "https://leetcode.com/problems/valid-anagram/"),
    ("Valid Palindrome", "Two Pointers", "https://leetcode.com/problems/valid-palindrome/"),
    ("Longest Palindromic Substring", "Dynamic Programming", "https://leetcode.com/problems/longest-palindromic-substring/"),
    ("Palindromic Substrings", "Dynamic Programming", "https://leetcode.com/problems/palindromic-substrings/"),
    ("Encode and Decode Strings", "String", "https://leetcode.com/problems/encode-and-decode-strings/"),
    ("Longest Substring Without Repeating Characters", "Sliding Window", "https://leetcode.com/problems/longest-substring-without-repeating-characters/"),
    ("Longest Repeating Character Replacement", "Sliding Window", "https://leetcode.com/problems/longest-repeating-character-replacement/"),
    ("Minimum Window Substring", "Sliding Window", "https://leetcode.com/problems/minimum-window-substring/"),
    ("Valid Sudoku", "Hash Set", "https://leetcode.com/problems/valid-sudoku/"),
    ("Word Search", "Backtracking", "https://leetcode.com/problems/word-search/"),
    ("Longest Consecutive Sequence", "Hash Set", "https://leetcode.com/problems/longest-consecutive-sequence/"),
    ("Set Matrix Zeroes", "Matrix", "https://leetcode.com/problems/set-matrix-zeroes/"),
    ("Spiral Matrix", "Matrix", "https://leetcode.com/problems/spiral-matrix/"),
    ("Rotate Image", "Matrix", "https://leetcode.com/problems/rotate-image/"),
    ("Word Break", "Dynamic Programming", "https://leetcode.com/problems/word-break/"),
    ("Combination Sum", "Backtracking", "https://leetcode.com/problems/combination-sum/"),
    ("Permutations", "Backtracking", "https://leetcode.com/problems/permutations/"),
    ("Subsets", "Backtracking", "https://leetcode.com/problems/subsets/"),
    ("Combination Sum II", "Backtracking", "https://leetcode.com/problems/combination-sum-ii/"),
    ("Letter Combinations of a Phone Number", "Backtracking", "https://leetcode.com/problems/letter-combinations-of-a-phone-number/"),
    ("Generate Parentheses", "Backtracking", "https://leetcode.com/problems/generate-parentheses/"),
    ("Merge k Sorted Lists", "Heap", "https://leetcode.com/problems/merge-k-sorted-lists/"),
    ("Top K Frequent Elements", "Heap / Bucket Sort", "https://leetcode.com/problems/top-k-frequent-elements/"),
    ("Find Median from Data Stream", "Heap", "https://leetcode.com/problems/find-median-from-data-stream/"),
    ("Kth Largest Element in an Array", "Heap", "https://leetcode.com/problems/kth-largest-element-in-an-array/"),
    ("Number of Islands", "DFS / BFS", "https://leetcode.com/problems/number-of-islands/"),
    ("Clone Graph", "DFS / BFS", "https://leetcode.com/problems/clone-graph/"),
    ("Course Schedule", "Graph / Topological Sort", "https://leetcode.com/problems/course-schedule/"),
    ("Pacific Atlantic Water Flow", "DFS / BFS", "https://leetcode.com/problems/pacific-atlantic-water-flow/"),
    ("Surrounded Regions", "DFS / BFS", "https://leetcode.com/problems/surrounded-regions/"),
    ("Rotting Oranges", "BFS", "https://leetcode.com/problems/rotting-oranges/"),
    ("Walls and Gates", "BFS", "https://leetcode.com/problems/walls-and-gates/"),
    ("Maximum Depth of Binary Tree", "DFS", "https://leetcode.com/problems/maximum-depth-of-binary-tree/"),
    ("Invert Binary Tree", "DFS", "https://leetcode.com/problems/invert-binary-tree/"),
    ("Diameter of Binary Tree", "DFS", "https://leetcode.com/problems/diameter-of-binary-tree/"),
    ("Balanced Binary Tree", "DFS", "https://leetcode.com/problems/balanced-binary-tree/"),
    ("Same Tree", "DFS", "https://leetcode.com/problems/same-tree/"),
    ("Subtree of Another Tree", "DFS", "https://leetcode.com/problems/subtree-of-another-tree/"),
    ("Lowest Common Ancestor of BST", "BST", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/"),
    ("Binary Tree Level Order Traversal", "BFS", "https://leetcode.com/problems/binary-tree-level-order-traversal/"),
    ("Serialize and Deserialize Binary Tree", "Tree", "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/"),
    ("Construct Binary Tree from Preorder and Inorder", "Tree Construction", "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/"),
    ("Validate Binary Search Tree", "DFS", "https://leetcode.com/problems/validate-binary-search-tree/"),
    ("Kth Smallest Element in a BST", "BST / Inorder", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/"),
    ("Implement Trie", "Trie", "https://leetcode.com/problems/implement-trie-prefix-tree/"),
    ("Add and Search Word - Data structure design", "Trie", "https://leetcode.com/problems/add-and-search-word-data-structure-design/"),
    ("Word Search II", "Trie + Backtracking", "https://leetcode.com/problems/word-search-ii/"),
    ("Find All Anagrams in a String", "Sliding Window", "https://leetcode.com/problems/find-all-anagrams-in-a-string/"),
    ("Minimum Number of Arrows to Burst Balloons", "Greedy", "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/"),
    ("Non-overlapping Intervals", "Greedy", "https://leetcode.com/problems/non-overlapping-intervals/"),
    ("Meeting Rooms", "Intervals", "https://leetcode.com/problems/meeting-rooms/"),
    ("Meeting Rooms II", "Heap / Intervals", "https://leetcode.com/problems/meeting-rooms-ii/"),
    ("Task Scheduler", "Greedy / Heap", "https://leetcode.com/problems/task-scheduler/"),
    ("Trapping Rain Water", "Two Pointers / Stack", "https://leetcode.com/problems/trapping-rain-water/"),
    ("Evaluate Reverse Polish Notation", "Stack", "https://leetcode.com/problems/evaluate-reverse-polish-notation/"),
    ("Basic Calculator", "Stack", "https://leetcode.com/problems/basic-calculator/"),
    ("Implement Stack using Queues", "Stack / Queue", "https://leetcode.com/problems/implement-stack-using-queues/"),
    ("Implement Queue using Stacks", "Stack / Queue", "https://leetcode.com/problems/implement-queue-using-stacks/"),
    ("LRU Cache", "LinkedHashMap / Design", "https://leetcode.com/problems/lru-cache/"),
    ("Min Stack", "Stack", "https://leetcode.com/problems/min-stack/"),
    ("Valid Palindrome II", "Two Pointers", "https://leetcode.com/problems/valid-palindrome-ii/"),
    ("Find Peak Element", "Binary Search", "https://leetcode.com/problems/find-peak-element/"),
    ("Search a 2D Matrix", "Binary Search", "https://leetcode.com/problems/search-a-2d-matrix/"),
    ("Pow(x, n)", "Recursion / Binary Exponentiation", "https://leetcode.com/problems/powx-n/"),
    ("Majority Element", "Boyer-Moore", "https://leetcode.com/problems/majority-element/"),
    ("Reverse Linked List", "Linked List", "https://leetcode.com/problems/reverse-linked-list/"),
    ("Merge Two Sorted Lists", "Linked List", "https://leetcode.com/problems/merge-two-sorted-lists/"),
    ("Linked List Cycle", "Linked List / Two Pointers", "https://leetcode.com/problems/linked-list-cycle/"),
    ("Remove Nth Node From End of List", "Linked List / Two Pointers", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/"),
    ("Reorder List", "Linked List / Two Pointers", "https://leetcode.com/problems/reorder-list/"),
    ("Find the Duplicate Number", "Binary Search / Cycle Detection", "https://leetcode.com/problems/find-the-duplicate-number/"),
    ("Missing Number", "Math / Bit Manipulation", "https://leetcode.com/problems/missing-number/"),
    ("Sum of Two Integers", "Bit Manipulation", "https://leetcode.com/problems/sum-of-two-integers/"),
    ("Number of 1 Bits", "Bit Manipulation", "https://leetcode.com/problems/number-of-1-bits/"),
    ("Counting Bits", "Bit Manipulation / DP", "https://leetcode.com/problems/counting-bits/"),
    ("Reverse Bits", "Bit Manipulation", "https://leetcode.com/problems/reverse-bits/"),
    ("House Robber", "DP", "https://leetcode.com/problems/house-robber/"),
    ("House Robber II", "DP", "https://leetcode.com/problems/house-robber-ii/"),
    ("Coin Change", "DP", "https://leetcode.com/problems/coin-change/"),
    ("Maximum Product Subarray", "DP", "https://leetcode.com/problems/maximum-product-subarray/"),
    ("Climbing Stairs", "DP", "https://leetcode.com/problems/climbing-stairs/"),
    ("Longest Increasing Subsequence", "DP", "https://leetcode.com/problems/longest-increasing-subsequence/"),
    ("Partition Equal Subset Sum", "DP / Subset Sum", "https://leetcode.com/problems/partition-equal-subset-sum/")
]

# Generate markdown table
table_md = "| No. | Problem | Pattern | Link | Done |\n"
table_md += "|-----|---------|---------|------|------|\n"
for idx, (title, pattern, url) in enumerate(leetcode_questions, 1):
    table_md += f"| {idx} | {title} | {pattern} | [🔗 Link]({url}) | ⬜ |\n"

table_md[:2000]  # preview the first part

